artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  vectorizer_path: artifacts/data_transformation/cv.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/X_train.npz
  test_data_path: artifacts/data_transformation/X_test.npz
  train_label_path: artifacts/data_transformation/y_train.csv
  test_label_path: artifacts/data_transformation/y_test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts\model_trainer\model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
